name: Get Submodules
description: |
  Get your submodules, including those that have GitLab remotes
runs:
  using: node16
  main: index.js

inputs:
  depth:
    description: The depth at which to clone each submodule at. Should be an integer.
  fetch-modified-only:
    description: Only fetches submodules modified by the latest push or by a pull request.
  enforce-https:
    description: Fails the action if a submodule uses non HTTPS clone urls, such as SSH. Otherwise, will temporarily convert SSH clone URLs to HTTPS clone URLs so they can be pulled.
