on:
  push:
    branches:
      - main
    paths:
      - addons/**
  pull_request:
    branches:
      - main
    paths:
      - addons/**

jobs:
  build:
    name: Get Addon Metadata
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        name: Checkout LLS-Addons
        with:
          fetch-depth: 0

      # Use custom action to get submodules
      # This allows us to get submodules that live on GitLab
      - uses: ./.github/actions/check_submodule
        with:
          fetch-modified-only: true
          enforce-https: true

      # Custom action that gets metadata on each addon
      - uses: dsaltares/fetch-gh-release-asset@1.1.0
        name: Get submodule metadata fetching action
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repo: LuaLS/LLS-Addons-Action
          file: dist.zip
          target: action.zip
      - name: Unzip custom action
        run: unzip action.zip -d action
      - uses: ./action/dist
        name: Get Addon Metadata

      # Commit new metadata
      - name: Commit Metadata
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "chore: Update Addon Metadata"
          file_pattern: addons/*/info.json
